Setup project & add feature flag API
4Com/vue-azure-app-configuration pull request #1
Opened 2023-01-25 16:24 UTC by osawyer

2023-01-27 14:13 UTC, kev24uk requested changes

2023-01-27 14:13 UTC, kev24uk commented on src/featureFlags.js
> +
Should we have an "isFeatureFlagEnabledForUserAsync" method too?

2023-02-01 13:17 UTC, osawyer commented on src/featureFlags.js
> +
Added

2023-02-01 13:25 UTC, kev24uk requested changes

2023-02-01 13:25 UTC, kev24uk commented on README.md
> +
Add isFeatureFlagEnabledForUserAsync here

2023-02-01 13:29 UTC, osawyer commented on README.md
> +
Ah yes! Done.

2023-02-01 13:50 UTC, kev24uk approved these changes

2023-02-01 13:53 UTC, merged